apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.bitfusion.io-cfg
  labels:
    app: bwki
webhooks:
  - name: bwkival.bitfusion.io
    clientConfig:
      service:
        name: bwki-webhook-svc
        namespace: bwki
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    admissionReviewVersions: [ "v1", "v1beta1" ]
    sideEffects: None
    timeoutSeconds: 5
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
